---
# default values for openstack umbrella chart
# Global overrides for subcharts

global:
  subchart_release_name: true

helm-toolkit:
  enabled: true

rabbitmq:
  enabled: true
  volume:
    enabled: false
  pod:
    replicas:
      server: 1

mariadb:
  enabled: true
  pod:
    replicas:
      server: 1
  volume:
    enabled: false
    use_local_path_for_single_pod_cluster:
      enabled: true

memcached:
  enabled: true

keystone:
  enabled: true

heat:
  enabled: true

glance:
  enabled: true
  storage: pvc
  volume:
    class_name: standard
