manifests:
  # NOTE(lamt): The nova-consoleauth service has been removed. It was
  # deprecated since the 18.0.0 (Rocky) release.
  # See: https://docs.openstack.org/releasenotes/nova/train.html
  deployment_consoleauth: false
  # NOTE(lamt): Placement code was extracted from nova post Stein.
  # A placement chart will need to be deployed to replace.
  # See: https://docs.openstack.org/releasenotes/nova/train.html
  deployment_placement: false
