---
images:
  tags:
    bootstrap: "docker.io/openstackhelm/heat:train-ubuntu_bionic"
    db_drop: "docker.io/openstackhelm/heat:train-ubuntu_bionic"
    db_init: "docker.io/openstackhelm/heat:train-ubuntu_bionic"
    ks_user: "docker.io/openstackhelm/heat:train-ubuntu_bionic"
    ks_service: "docker.io/openstackhelm/heat:train-ubuntu_bionic"
    ks_endpoints: "docker.io/openstackhelm/heat:train-ubuntu_bionic"
    nova_api: "docker.io/openstackhelm/nova:train-ubuntu_bionic"
    nova_cell_setup: "docker.io/openstackhelm/nova:train-ubuntu_bionic"
    nova_cell_setup_init: "docker.io/openstackhelm/heat:train-ubuntu_bionic"
    nova_compute: "docker.io/openstackhelm/nova:train-ubuntu_bionic"
    nova_compute_ssh: "docker.io/openstackhelm/nova:train-ubuntu_bionic"
    nova_conductor: "docker.io/openstackhelm/nova:train-ubuntu_bionic"
    nova_db_sync: "docker.io/openstackhelm/nova:train-ubuntu_bionic"
    nova_novncproxy: "docker.io/openstackhelm/nova:train-ubuntu_bionic"
    nova_novncproxy_assets: "docker.io/openstackhelm/nova:train-ubuntu_bionic"
    nova_placement: "docker.io/openstackhelm/placement:master-ubuntu_bionic-20200207"
    nova_scheduler: "docker.io/openstackhelm/nova:train-ubuntu_bionic"
    nova_spiceproxy: "docker.io/openstackhelm/nova:train-ubuntu_bionic"
    nova_spiceproxy_assets: "docker.io/openstackhelm/nova:train-ubuntu_bionic"
    nova_service_cleaner: "docker.io/openstackhelm/ceph-config-helper:latest-ubuntu_bionic"
manifests:
  # NOTE(lamt): The nova-consoleauth service has been removed. It was
  # deprecated since the 18.0.0 (Rocky) release.
  # See: https://docs.openstack.org/releasenotes/nova/train.html
  deployment_consoleauth: false
  # NOTE(lamt): Placement code was extracted from nova post Stein.
  # A placement chart will need to be deployed to replace.
  # See: https://docs.openstack.org/releasenotes/nova/train.html
  deployment_placement: false
